### ISSUE TITLE
Seems like a text/button color conflict with Starfinder Ruleset

### ISSUE THREAD

**Issue by pschlax2** [seanmccarty/RequestedRolls#45]
Hi there.  I love this addon and use it weekly with my SFRPG campaign.  At some point in the last month something changed and now the text on all of the buttons is indistinguishable from the color on the buttons.  I think the text might be black and the buttons are a very dark blue.  If this is a problem on my end, I'm sorry for submitting this.  However, if it really is problem you can fix, I would be very grateful!

![2024-01-16_12-35-10](https://github.com/seanmccarty/RequestedRolls/assets/22963360/d1bf8e47-8b66-4f98-a404-5048daaa8051)

**Comment by seanmccarty** [comment]
I'm seeing the issue. Something just have changed with the theming, and I'll take a look soon.

**Comment by pschlax2** [comment]
Thanks so much!

**Comment by seanmccarty** [comment]
Fixed with release 2.14.1. Available on Forge.

**Comment by seanmccarty** [comment]
Also, I really enjoyed the fact that you open an issue on GitHub. Thank you for reporting this.

**Comment by pschlax2** [comment]
I just installed the update and took a peek.  It looks great and, more
importantly, it is usable!
Thanks so much for your work on this.  It is probably my most used add on
for FG.  The fact that it works for 5e, Pathfinder, and Starfinder is solid
gold to me.
Also, no problem regarding the GitHub request.  For versioning and tracking
changes with code, that is definitely the way to go!

Best,
-Pete
